import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import express from "express";
import {
  loginUser,
  scriptLoginWithPassword,
  scriptLoginWithSavedKey,
  validateToken,
  verifyToken,
  updateScriptPresence,
  fetchPendingClientCommands,
  ackClientCommand,
  enqueuePeerClientAction,
  getScriptAccessStatus,
  listOnlinePeers,
  getFriends,
  sendFriendRequest,
  acceptFriendRequest,
  denyFriendRequest,
  removeFriend,
  requestJoinFriend,
  respondToJoinRequest,
  sendFriendMessage,
  getFriendMessages,
} from "./auth.js";
import { prisma } from "./db.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export function createApi() {
  const app = express();
  app.set("trust proxy", true);
  const getRequestIp = (req) => {
    const forwarded = req.headers["x-forwarded-for"];
    if (typeof forwarded === "string" && forwarded.trim() !== "") {
      return forwarded.split(",")[0].trim();
    }
    return req.ip || req.socket?.remoteAddress || null;
  };

  const sendAuthFailure = (res, err, fallbackStatus = 401) => {
    if (err && err.authCode) {
      return res.status(fallbackStatus).json({
        ok: false,
        error: err.message,
        code: err.authCode,
        lockoutUntil: err.lockoutUntil || undefined,
      });
    }
    return res.status(fallbackStatus).json({ ok: false, error: err?.message || "error" });
  };
  const extractToken = (req) => {
    const auth = req.headers.authorization || "";
    const m = auth.match(/^Bearer\s+(.+)$/i);
    if (m && m[1]) return m[1];
    if (req.body && typeof req.body.token === "string" && req.body.token.trim() !== "") {
      return req.body.token.trim();
    }
    return null;
  };

  // ── Script serving ────────────────────────────────────────────────

  // Helper: serve first-found file from candidate paths.
  const serveFirstFound = (res, candidates, notFoundMsg) => {
    for (const p of candidates) {
      try {
        if (fs.existsSync(p)) {
          res.type("text/plain; charset=utf-8");
          return res.send(fs.readFileSync(p, "utf8"));
        }
      } catch {
        // try next
      }
    }
    res.status(404).type("text/plain").send(notFoundMsg);
  };

  // Public Loader.lua — the new entry point. Small script with login UI + auth.
  app.get("/Loader.lua", (_req, res) => {
    serveFirstFound(res,
      [
        path.join(__dirname, "../../Loader.lua"),
        path.join(__dirname, "../public/Loader.lua"),
      ],
      "-- Loader.lua not found on server.\n"
    );
  });

  // Protected Admin.lua — requires valid JWT via ?token= query param.
  // Uses lightweight verifyToken (no DB) for fast script serving.
  app.get("/Admin.lua", (req, res) => {
    const token = req.query.token || null;
    if (!token) {
      return res.status(401).type("text/plain").send("-- Token required for Admin.lua. Run Loader.lua first.\n");
    }
    let payload;
    try {
      payload = verifyToken(token);
    } catch {
      return res.status(401).type("text/plain").send("-- Invalid or expired token. Re-run Loader.lua to authenticate.\n");
    }

    const candidates = [
      path.join(__dirname, "../protected/Admin.lua"),
      path.join(__dirname, "../../Admin.lua"),
    ];
    let scriptContent = null;
    for (const p of candidates) {
      try {
        if (fs.existsSync(p)) {
          scriptContent = fs.readFileSync(p, "utf8");
          break;
        }
      } catch {
        // try next
      }
    }
    if (!scriptContent) {
      return res.status(404).type("text/plain").send("-- Admin.lua not found on server.\n");
    }

    // Embed auth context at the top so Admin.lua can read token without filesystem access.
    const authHeader = [
      "-- Auto-generated by server — auth context from Loader.lua",
      "_G.UA_AuthContext = _G.UA_AuthContext or {}",
      "_G.UA_AuthContext.token = " + JSON.stringify(token),
      "_G.UA_AuthContext.username = " + JSON.stringify(payload.username || ""),
      "_G.UA_AuthContext.tier = " + JSON.stringify(payload.tier || "Member"),
      "_G.UA_AuthContext.sub = " + JSON.stringify(payload.sub),
      "_G.UA_AuthContext.jti = " + JSON.stringify(payload.jti || ""),
      "_G.UA_RUNTIME = _G.UA_RUNTIME or {}",
      "",
    ].join("\n");

    res.set("Cache-Control", "no-store");
    res.type("text/plain; charset=utf-8");
    res.send(authHeader + scriptContent);
  });

  // Backward compat: /UniversalAdmin.lua now serves Loader.lua so old loadstrings still work.
  // Users who already have the old loader will get the new secure Loader.lua automatically.
  app.get("/UniversalAdmin.lua", (_req, res) => {
    serveFirstFound(res,
      [
        path.join(__dirname, "../../Loader.lua"),
        path.join(__dirname, "../public/Loader.lua"),
        path.join(__dirname, "../../UniversalAdmin.lua"),
        path.join(__dirname, "../public/UniversalAdmin.lua"),
      ],
      "-- UniversalAdmin.lua not found on server. Use /Loader.lua instead.\n"
    );
  });

  app.use(express.static(path.join(__dirname, "../public")));
  app.use(express.json());

  app.get("/health", (_req, res) => {
    res.json({ ok: true });
  });

  app.post("/auth/login", async (req, res) => {
    try {
      const { username, password } = req.body || {};
      if (!username || !password) {
        return res.status(400).json({ ok: false, error: "username and password required" });
      }
      const result = await loginUser({ username, password });
      res.json({ ok: true, ...result });
    } catch (err) {
      res.status(401).json({ ok: false, error: err.message });
    }
  });

  app.post("/auth/script-login", async (req, res) => {
    try {
      const { username, password, hwid } = req.body || {};
      if (!username || !password) {
        return res.status(400).json({ ok: false, error: "username and password required" });
      }
      const result = await scriptLoginWithPassword({
        username,
        password,
        hwid,
        ip: getRequestIp(req),
      });
      res.json({ ok: true, ...result });
    } catch (err) {
      return sendAuthFailure(res, err);
    }
  });

  app.post("/auth/script-login-key", async (req, res) => {
    try {
      const { username, key, hwid } = req.body || {};
      if (!username) {
        return res.status(400).json({ ok: false, error: "username required" });
      }
      const result = await scriptLoginWithSavedKey({
        username,
        keyCode: key,
        hwid,
        ip: getRequestIp(req),
      });
      res.json({ ok: true, ...result });
    } catch (err) {
      return sendAuthFailure(res, err);
    }
  });

  app.post("/auth/access-status", async (req, res) => {
    try {
      const { hwid } = req.body || {};
      const status = await getScriptAccessStatus({
        hwid,
        ip: getRequestIp(req),
      });
      res.json({ ok: true, ...status });
    } catch (err) {
      return sendAuthFailure(res, err);
    }
  });

  app.post("/auth/validate", (req, res) => {
    (async () => {
      const { token } = req.body || {};
      if (!token) return res.status(400).json({ ok: false, error: "token required" });
      const payload = await validateToken(token);
      res.json({ ok: true, payload });
    })().catch(() => {
      res.status(401).json({ ok: false, error: "invalid token" });
    });
  });

  app.post("/client/presence", async (req, res) => {
    try {
      const token = extractToken(req);
      if (!token) return res.status(401).json({ ok: false, error: "token required" });
      const { robloxUserId, robloxUsername, placeId, gameId, hwid, accentPrimary } = req.body || {};
      await updateScriptPresence(token, {
        robloxUserId,
        robloxUsername,
        placeId,
        gameId,
        hwid,
        accentPrimary,
        ipAddress: getRequestIp(req),
      });
      const roster = await listOnlinePeers(token, {});
      res.json({ ok: true, peers: roster.peers || [] });
    } catch (err) {
      res.status(401).json({ ok: false, error: err.message });
    }
  });

  app.get("/client/commands", async (req, res) => {
    try {
      const token = extractToken(req);
      if (!token) return res.status(401).json({ ok: false, error: "token required" });
      const commands = await fetchPendingClientCommands(token);
      res.json({ ok: true, commands });
    } catch (err) {
      res.status(401).json({ ok: false, error: err.message });
    }
  });

  // POST variant is more executor-friendly for client polling than GET with custom headers.
  app.post("/client/commands", async (req, res) => {
    try {
      const token = extractToken(req);
      if (!token) return res.status(401).json({ ok: false, error: "token required" });
      const commands = await fetchPendingClientCommands(token);
      res.json({ ok: true, commands });
    } catch (err) {
      res.status(401).json({ ok: false, error: err.message });
    }
  });

  app.post("/client/ack", async (req, res) => {
    try {
      const token = extractToken(req);
      if (!token) return res.status(401).json({ ok: false, error: "token required" });
      const { commandId, status, error } = req.body || {};
      await ackClientCommand(token, commandId, status, error);
      res.json({ ok: true });
    } catch (err) {
      res.status(401).json({ ok: false, error: err.message });
    }
  });

  app.post("/client/peer-action", async (req, res) => {
    try {
      const token = extractToken(req);
      if (!token) return res.status(401).json({ ok: false, error: "token required" });
      const { target, action, payload } = req.body || {};
      if (!target || !action) {
        return res.status(400).json({ ok: false, error: "target and action required" });
      }
      const out = await enqueuePeerClientAction(token, {
        targetIdentity: target,
        action,
        payload: (payload && typeof payload === "object") ? payload : {},
      });
      res.json({ ok: true, ...out });
    } catch (err) {
      res.status(400).json({ ok: false, error: err.message });
    }
  });

  app.post("/session/start", async (req, res) => {
    try {
      const { token, robloxUserId, robloxGameId, robloxPlaceId } = req.body || {};
      const payload = await validateToken(token);
      await prisma.session.update({
        where: { tokenJti: payload.jti },
        data: {
          robloxUserId: robloxUserId ? String(robloxUserId) : null,
          robloxGameId: robloxGameId ? String(robloxGameId) : null,
          robloxPlaceId: robloxPlaceId ? String(robloxPlaceId) : null,
          startedAt: new Date(),
          lastSeenAt: new Date(),
        },
      });
      res.json({ ok: true });
    } catch (err) {
      res.status(401).json({ ok: false, error: err.message });
    }
  });

  // ── Friends ──────────────────────────────────────────

  const friendsAuth = (req) => {
    const tok = extractToken(req);
    if (!tok) return null;
    return validateToken(tok).catch(() => null);
  };

  const requireFriendsAuth = async (req, res) => {
    const tok = extractToken(req);
    if (!tok) { res.status(401).json({ ok: false, error: "token required" }); return null; }
    try {
      return await validateToken(tok);
    } catch {
      res.status(401).json({ ok: false, error: "invalid token" });
      return null;
    }
  };

  app.get("/friends", async (req, res) => {
    try {
      const payload = await requireFriendsAuth(req, res);
      if (!payload) return;
      const userId = Number(payload.sub);
      const data = await getFriends(userId);
      res.json({ ok: true, ...data });
    } catch (err) {
      res.status(400).json({ ok: false, error: err.message });
    }
  });

  app.post("/friends/request", async (req, res) => {
    try {
      const payload = await requireFriendsAuth(req, res);
      if (!payload) return;
      const { username } = req.body || {};
      if (!username) return res.status(400).json({ ok: false, error: "username required" });
      const out = await sendFriendRequest(Number(payload.sub), username);
      res.json({ ok: true, ...out });
    } catch (err) {
      res.status(400).json({ ok: false, error: err.message });
    }
  });

  // Keep /friends/add as alias for backwards compat
  app.post("/friends/add", async (req, res) => {
    try {
      const payload = await requireFriendsAuth(req, res);
      if (!payload) return;
      const { username } = req.body || {};
      if (!username) return res.status(400).json({ ok: false, error: "username required" });
      const out = await sendFriendRequest(Number(payload.sub), username);
      res.json({ ok: true, ...out });
    } catch (err) {
      res.status(400).json({ ok: false, error: err.message });
    }
  });

  app.post("/friends/accept", async (req, res) => {
    try {
      const payload = await requireFriendsAuth(req, res);
      if (!payload) return;
      const { requestId } = req.body || {};
      if (requestId == null) return res.status(400).json({ ok: false, error: "requestId required" });
      const out = await acceptFriendRequest(Number(payload.sub), requestId);
      res.json({ ok: true, ...out });
    } catch (err) {
      res.status(400).json({ ok: false, error: err.message });
    }
  });

  app.post("/friends/deny", async (req, res) => {
    try {
      const payload = await requireFriendsAuth(req, res);
      if (!payload) return;
      const { requestId } = req.body || {};
      if (requestId == null) return res.status(400).json({ ok: false, error: "requestId required" });
      const out = await denyFriendRequest(Number(payload.sub), requestId);
      res.json({ ok: true, ...out });
    } catch (err) {
      res.status(400).json({ ok: false, error: err.message });
    }
  });

  app.post("/friends/remove", async (req, res) => {
    try {
      const payload = await requireFriendsAuth(req, res);
      if (!payload) return;
      const { username } = req.body || {};
      if (!username) return res.status(400).json({ ok: false, error: "username required" });
      const out = await removeFriend(Number(payload.sub), username);
      res.json({ ok: true, ...out });
    } catch (err) {
      res.status(400).json({ ok: false, error: err.message });
    }
  });

  app.post("/friends/join", async (req, res) => {
    try {
      const payload = await requireFriendsAuth(req, res);
      if (!payload) return;
      const { username } = req.body || {};
      if (!username) return res.status(400).json({ ok: false, error: "username required" });
      const out = await requestJoinFriend(Number(payload.sub), username);
      res.json({ ok: true, ...out });
    } catch (err) {
      res.status(400).json({ ok: false, error: err.message });
    }
  });

  app.post("/friends/join-respond", async (req, res) => {
    try {
      const payload = await requireFriendsAuth(req, res);
      if (!payload) return;
      const { username, accepted } = req.body || {};
      if (!username) return res.status(400).json({ ok: false, error: "username required" });
      const out = await respondToJoinRequest(Number(payload.sub), username, accepted === true);
      res.json({ ok: true, ...out });
    } catch (err) {
      res.status(400).json({ ok: false, error: err.message });
    }
  });

  app.post("/friends/message", async (req, res) => {
    try {
      const payload = await requireFriendsAuth(req, res);
      if (!payload) return;
      const { username, content, text } = req.body || {};
      const msgContent = content || text;
      if (!username || !msgContent) return res.status(400).json({ ok: false, error: "username and content required" });
      const out = await sendFriendMessage(Number(payload.sub), username, msgContent);
      res.json({ ok: true, ...out });
    } catch (err) {
      res.status(400).json({ ok: false, error: err.message });
    }
  });

  app.get("/friends/messages", async (req, res) => {
    try {
      const payload = await requireFriendsAuth(req, res);
      if (!payload) return;
      const friendUsername = req.query.with || null;
      const data = await getFriendMessages(Number(payload.sub), friendUsername);
      res.json({ ok: true, ...data });
    } catch (err) {
      res.status(400).json({ ok: false, error: err.message });
    }
  });

  app.post("/session/end", async (req, res) => {
    try {
      const { token } = req.body || {};
      const payload = await validateToken(token);
      await prisma.session.update({
        where: { tokenJti: payload.jti },
        data: { endedAt: new Date(), revoked: true },
      });
      res.json({ ok: true });
    } catch (err) {
      res.status(401).json({ ok: false, error: err.message });
    }
  });

  return app;
}
